spring.application.name=backend
spring.config.import=optional:file:.env[.properties],optional:file:backend/.env[.properties]
server.port=${PORT:8080}
server.address=0.0.0.0
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret =${JWT_SECRET}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

cloudinary.cloud_name=${CLOUDINARY_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

razorpay.key-id=${RAZORPAY_TEST_KEY_ID}
razorpay.key-secret=${RAZORPAY_TEST_KEY_SECRET}

resend.api-key=${RESEND_API_KEY}
mail.from=orders@inknwall.in