spring.application.name=backend
server.port=8080
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/inknwall}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:chicken65}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
cloudinary.cloud_name=dmtnw2ago
cloudinary.api_key=366726912673698
cloudinary.api_secret=EnFhvWAp4eW8cHB6BiWjNkcSCVk

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=inknwall@gmail.com
spring.mail.password=qiljjnslrtyrhvia
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true